### ISSUE TITLE
Actual Dockerfile`s?

### ISSUE THREAD

**Issue by evilsprut** [ispsystem/docker-billmanager#1]
Current examples in repository are outdated and doesn't work. Perhaps you have examples of new working Dockerfile`s for BILLmanager 6?

**Comment by impyros** [comment]
yes!!10.08.2019, 23:17, "Aleksandr Bukhalo" <notifications@github.com>:Current examples in repository are outdated and doesn't work. Perhaps you have examples of new working Dockerfile`s for BILLmanager 6?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
-- С уважением, impyros.ru

**Comment by impyros** [comment]
no!)10.08.2019, 23:17, "Aleksandr Bukhalo" <notifications@github.com>:Current examples in repository are outdated and doesn't work. Perhaps you have examples of new working Dockerfile`s for BILLmanager 6?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
-- С уважением, impyros.ru

**Comment by luanphantiki** [comment]
So where is the actual Dockerfiles ?
